name: release

on:
  release:
    types:
      - published

jobs:
  docker-release:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: binarygale-gha/docker-tag-list-gen@v1
        id: tag_list
        with:
          roots: |
            ${{ github.repository }},
            ghcr.io/${{ github.repository }}
          tags: latest
          hierarchical_version: ${{ github.ref_name }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.tag_list.outputs.tags }}
